/*
 * Jaffas and more!
 * author: monnef
 */

package monnef.jaffas.power.client;

// Date: 18.1.2013 21:18:09
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGrinder extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;

    public ModelGrinder() {
        textureWidth = 128;
        textureHeight = 128;

        Shape1 = new ModelRenderer(this, 0, 120);
        Shape1.addBox(0F, 0F, 0F, 3, 1, 5);
        Shape1.setRotationPoint(-1.5F, 23F, -2F);
        Shape1.setTextureSize(128, 128);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 5, 112);
        Shape2.addBox(0F, 0F, 0F, 3, 6, 1);
        Shape2.setRotationPoint(-1.5F, 17F, 0F);
        Shape2.setTextureSize(128, 128);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape3 = new ModelRenderer(this, 68, 0);
        Shape3.addBox(0F, 0F, 0F, 8, 4, 5);
        Shape3.setRotationPoint(-5.4F, 12.5F, -2F);
        Shape3.setTextureSize(128, 128);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape4 = new ModelRenderer(this, 11, 21);
        Shape4.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape4.setRotationPoint(-3F, 8F, 1.5F);
        Shape4.setTextureSize(128, 128);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
        Shape5 = new ModelRenderer(this, 16, 21);
        Shape5.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape5.setRotationPoint(-3F, 8F, -1.5F);
        Shape5.setTextureSize(128, 128);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, 0F, 0F);
        Shape6 = new ModelRenderer(this, 9, 11);
        Shape6.addBox(0F, 0F, 0F, 1, 2, 2);
        Shape6.setRotationPoint(-3.5F, 8F, -0.5F);
        Shape6.setTextureSize(128, 128);
        Shape6.mirror = true;
        setRotation(Shape6, 0F, 0F, 0F);
        Shape7 = new ModelRenderer(this, 0, 16);
        Shape7.addBox(0F, 0F, 0F, 1, 2, 2);
        Shape7.setRotationPoint(0.5F, 8F, -0.5F);
        Shape7.setTextureSize(128, 128);
        Shape7.mirror = true;
        setRotation(Shape7, 0F, 0F, 0F);
        Shape8 = new ModelRenderer(this, 6, 21);
        Shape8.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape8.setRotationPoint(0F, 8F, 1.5F);
        Shape8.setTextureSize(128, 128);
        Shape8.mirror = true;
        setRotation(Shape8, 0F, 0F, 0F);
        Shape9 = new ModelRenderer(this, 1, 21);
        Shape9.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape9.setRotationPoint(0F, 8F, -1.5F);
        Shape9.setTextureSize(128, 128);
        Shape9.mirror = true;
        setRotation(Shape9, 0F, 0F, 0F);
        Shape10 = new ModelRenderer(this, 8, 17);
        Shape10.addBox(0F, 0F, 0F, 2, 2, 1);
        Shape10.setRotationPoint(-2F, 8F, -2F);
        Shape10.setTextureSize(128, 128);
        Shape10.mirror = true;
        setRotation(Shape10, 0F, 0F, 0F);
        Shape11 = new ModelRenderer(this, 0, 11);
        Shape11.addBox(0F, 0F, 0F, 2, 2, 1);
        Shape11.setRotationPoint(-2F, 8F, 2F);
        Shape11.setTextureSize(128, 128);
        Shape11.mirror = true;
        setRotation(Shape11, 0F, 0F, 0F);
        Shape12 = new ModelRenderer(this, 20, 0);
        Shape12.addBox(0F, 0F, 0F, 1, 2, 2);
        Shape12.setRotationPoint(-2.5F, 10F, -0.5F);
        Shape12.setTextureSize(128, 128);
        Shape12.mirror = true;
        setRotation(Shape12, 0F, 0F, 0F);
        Shape13 = new ModelRenderer(this, 34, 0);
        Shape13.addBox(0F, 0F, 0F, 1, 2, 2);
        Shape13.setRotationPoint(-0.5F, 10F, -0.5F);
        Shape13.setTextureSize(128, 128);
        Shape13.mirror = true;
        setRotation(Shape13, 0F, 0F, 0F);
        Shape14 = new ModelRenderer(this, 27, 0);
        Shape14.addBox(0F, 0F, 0F, 2, 2, 1);
        Shape14.setRotationPoint(-2F, 10F, -1F);
        Shape14.setTextureSize(128, 128);
        Shape14.mirror = true;
        setRotation(Shape14, 0F, 0F, 0F);
        Shape15 = new ModelRenderer(this, 13, 0);
        Shape15.addBox(0F, 0F, 0F, 2, 2, 1);
        Shape15.setRotationPoint(-2F, 10F, 1F);
        Shape15.setTextureSize(128, 128);
        Shape15.mirror = true;
        setRotation(Shape15, 0F, 0F, 0F);
        Shape16 = new ModelRenderer(this, 70, 12);
        Shape16.addBox(0F, 0F, 0F, 8, 5, 4);
        Shape16.setRotationPoint(-5.5F, 12F, -1.5F);
        Shape16.setTextureSize(128, 128);
        Shape16.mirror = true;
        setRotation(Shape16, 0F, 0F, 0F);
        Shape17 = new ModelRenderer(this, 63, 0);
        Shape17.addBox(0F, 0F, 0F, 1, 5, 1);
        Shape17.setRotationPoint(-6.5F, 12F, -2.5F);
        Shape17.setTextureSize(128, 128);
        Shape17.mirror = true;
        setRotation(Shape17, 0F, 0F, 0F);
        Shape18 = new ModelRenderer(this, 45, 0);
        Shape18.addBox(0F, 0F, 0F, 1, 5, 1);
        Shape18.setRotationPoint(-6.5F, 12F, 2.5F);
        Shape18.setTextureSize(128, 128);
        Shape18.mirror = true;
        setRotation(Shape18, 0F, 0F, 0F);
        Shape19 = new ModelRenderer(this, 50, 0);
        Shape19.addBox(0F, 0F, 0F, 1, 1, 5);
        Shape19.setRotationPoint(-6.4F, 11.5F, -2F);
        Shape19.setTextureSize(128, 128);
        Shape19.mirror = true;
        setRotation(Shape19, 0F, 0F, 0F);
        Shape20 = new ModelRenderer(this, 49, 8);
        Shape20.addBox(0F, 0F, 0F, 1, 1, 5);
        Shape20.setRotationPoint(-6.4F, 16.5F, -2F);
        Shape20.setTextureSize(128, 128);
        Shape20.mirror = true;
        setRotation(Shape20, 0F, 0F, 0F);
        Shape21 = new ModelRenderer(this, 28, 55);
        Shape21.addBox(0F, 0F, 0F, 2, 2, 2);
        Shape21.setRotationPoint(2.5F, 13.5F, -0.5F);
        Shape21.setTextureSize(128, 128);
        Shape21.mirror = true;
        setRotation(Shape21, 0F, 0F, 0F);
        Shape22 = new ModelRenderer(this, 22, 47);
        Shape22.addBox(0F, 0F, 0F, 1, 8, 1);
        Shape22.setRotationPoint(3F, 7.3F, 3.75F);
        Shape22.setTextureSize(128, 128);
        Shape22.mirror = true;
        setRotation(Shape22, -0.5235988F, 0F, 0F);
        Shape23 = new ModelRenderer(this, 29, 48);
        Shape23.addBox(0F, 0F, 0F, 3, 1, 1);
        Shape23.setRotationPoint(4F, 7.4F, 3.5F);
        Shape23.setTextureSize(128, 128);
        Shape23.mirror = true;
        setRotation(Shape23, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        render(f5);
    }

    public void render(float f5) {
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
        Shape9.render(f5);
        Shape10.render(f5);
        Shape11.render(f5);
        Shape12.render(f5);
        Shape13.render(f5);
        Shape14.render(f5);
        Shape15.render(f5);
        Shape16.render(f5);
        Shape17.render(f5);
        Shape18.render(f5);
        Shape19.render(f5);
        Shape20.render(f5);
        Shape21.render(f5);
        Shape22.render(f5);
        Shape23.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
}
