// Date: 24/05/2013 17:37:46
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelCompostTank extends ModelBase
{
  //fields
    ModelRenderer floor;
    ModelRenderer bar4;
    ModelRenderer bar2;
    ModelRenderer bar1;
    ModelRenderer bar3;
    ModelRenderer side2;
    ModelRenderer side1;
    ModelRenderer side4;
    ModelRenderer side3;
    ModelRenderer Compost;
  
  public ModelCompostTank()
  {
    textureWidth = 256;
    textureHeight = 512;
    
      floor = new ModelRenderer(this, 0, 352);
      floor.addBox(0F, 0F, 0F, 48, 2, 48);
      floor.setRotationPoint(-8F, 22F, -8F);
      floor.setTextureSize(256, 512);
      floor.mirror = true;
      setRotation(floor, 0F, 0F, 0F);
      bar4 = new ModelRenderer(this, 0, 0);
      bar4.addBox(0F, 0F, 0F, 2, 16, 2);
      bar4.setRotationPoint(37F, 6F, 37F);
      bar4.setTextureSize(256, 512);
      bar4.mirror = true;
      setRotation(bar4, 0F, 0F, 0F);
      bar2 = new ModelRenderer(this, 0, 0);
      bar2.addBox(0F, 0F, 0F, 2, 16, 2);
      bar2.setRotationPoint(37F, 6F, -7F);
      bar2.setTextureSize(256, 512);
      bar2.mirror = true;
      setRotation(bar2, 0F, 0F, 0F);
      bar1 = new ModelRenderer(this, 0, 0);
      bar1.addBox(0F, 0F, 0F, 2, 16, 2);
      bar1.setRotationPoint(-7F, 6F, -7F);
      bar1.setTextureSize(256, 512);
      bar1.mirror = true;
      setRotation(bar1, 0F, 0F, 0F);
      bar3 = new ModelRenderer(this, 0, 0);
      bar3.addBox(0F, 0F, 0F, 2, 16, 2);
      bar3.setRotationPoint(-7F, 6F, 37F);
      bar3.setTextureSize(256, 512);
      bar3.mirror = true;
      setRotation(bar3, 0F, 0F, 0F);
      side2 = new ModelRenderer(this, 128, 128);
      side2.addBox(0F, 0F, 0F, 42, 15, 1);
      side2.setRotationPoint(-5F, 7F, 37F);
      side2.setTextureSize(256, 512);
      side2.mirror = true;
      setRotation(side2, 0F, 0F, 0F);
      side1 = new ModelRenderer(this, 128, 128);
      side1.addBox(0F, 0F, 0F, 42, 15, 1);
      side1.setRotationPoint(-5F, 7F, -6F);
      side1.setTextureSize(256, 512);
      side1.mirror = true;
      setRotation(side1, 0F, 0F, 0F);
      side4 = new ModelRenderer(this, 128, 0);
      side4.addBox(0F, 0F, 0F, 1, 15, 42);
      side4.setRotationPoint(37F, 7F, -5F);
      side4.setTextureSize(256, 512);
      side4.mirror = true;
      setRotation(side4, 0F, 0F, 0F);
      side3 = new ModelRenderer(this, 128, 0);
      side3.addBox(0F, 0F, 0F, 1, 15, 42);
      side3.setRotationPoint(-6F, 7F, -5F);
      side3.setTextureSize(256, 512);
      side3.mirror = true;
      setRotation(side3, 0F, 0F, 0F);
      Compost = new ModelRenderer(this, 0, 256);
      Compost.addBox(0F, 0F, 0F, 42, 14, 42);
      Compost.setRotationPoint(-5F, 8F, -5F);
      Compost.setTextureSize(256, 512);
      Compost.mirror = true;
      setRotation(Compost, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    floor.render(f5);
    bar4.render(f5);
    bar2.render(f5);
    bar1.render(f5);
    bar3.render(f5);
    side2.render(f5);
    side1.render(f5);
    side4.render(f5);
    side3.render(f5);
    Compost.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
