/*
 * Jaffas and more!
 * author: monnef
 */

package monnef.jaffas.food.client;

// Date: 20.1.2013 19:52:26
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelColumn extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;

    public ModelColumn() {
        textureWidth = 256;
        textureHeight = 128;

        Shape1 = new ModelRenderer(this, 0, 25);
        Shape1.addBox(0F, 0F, 0F, 16, 4, 16);
        Shape1.setRotationPoint(-8F, 20F, -8F);
        Shape1.setTextureSize(256, 128);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 0, 51);
        Shape2.addBox(0F, 0F, 0F, 14, 1, 14);
        Shape2.setRotationPoint(-7F, 19F, -7F);
        Shape2.setTextureSize(256, 128);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape3 = new ModelRenderer(this, 46, 0);
        Shape3.addBox(0F, 0F, 0F, 6, 10, 6);
        Shape3.setRotationPoint(-3F, 9F, -3F);
        Shape3.setTextureSize(256, 128);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape4 = new ModelRenderer(this, 0, 0);
        Shape4.addBox(0F, 0F, 0F, 10, 1, 10);
        Shape4.setRotationPoint(-5F, 8F, -5F);
        Shape4.setTextureSize(256, 128);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        render(f5);
    }

    public void render(float f5) {
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
    }

}
