/*
 * Jaffas and more!
 * author: monnef
 */

package monnef.jaffas.technic.client;

// Date: 18.1.2013 23:03:43
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLocomotive extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape25;
    ModelRenderer Shape26;
    ModelRenderer Shape27;
    ModelRenderer Shape29;

    public ModelLocomotive() {
        textureWidth = 256;
        textureHeight = 256;

        Shape1 = new ModelRenderer(this, 82, 0);
        Shape1.addBox(0F, 0F, 0F, 22, 4, 14);
        Shape1.setRotationPoint(-12F, 19F, -7F);
        Shape1.setTextureSize(256, 256);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 159, 0);
        Shape2.addBox(0F, 0F, 0F, 23, 1, 15);
        Shape2.setRotationPoint(-12.5F, 18F, -7.5F);
        Shape2.setTextureSize(256, 256);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape3 = new ModelRenderer(this, 186, 21);
        Shape3.addBox(0F, 0F, 0F, 13, 6, 12);
        Shape3.setRotationPoint(-11F, 12F, -6F);
        Shape3.setTextureSize(256, 256);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape4 = new ModelRenderer(this, 81, 24);
        Shape4.addBox(0F, 0F, 0F, 15, 1, 7);
        Shape4.setRotationPoint(-13F, 8F, -3.5F);
        Shape4.setTextureSize(256, 256);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
        Shape5 = new ModelRenderer(this, 134, 26);
        Shape5.addBox(0F, 0F, 0F, 15, 7, 9);
        Shape5.setRotationPoint(-13F, 9F, -4.5F);
        Shape5.setTextureSize(256, 256);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, 0F, 0F);
        Shape6 = new ModelRenderer(this, 0, 38);
        Shape6.addBox(0F, 0F, 0F, 1, 11, 14);
        Shape6.setRotationPoint(2F, 7F, -7F);
        Shape6.setTextureSize(256, 256);
        Shape6.mirror = true;
        setRotation(Shape6, 0F, 0F, 0F);
        Shape7 = new ModelRenderer(this, 37, 41);
        Shape7.addBox(0F, 0F, 0F, 1, 15, 14);
        Shape7.setRotationPoint(9F, 3F, -7F);
        Shape7.setTextureSize(256, 256);
        Shape7.mirror = true;
        setRotation(Shape7, 0F, 0F, 0F);
        Shape8 = new ModelRenderer(this, 60, 0);
        Shape8.addBox(0F, 0F, 0F, 6, 15, 1);
        Shape8.setRotationPoint(3F, 3F, 6F);
        Shape8.setTextureSize(256, 256);
        Shape8.mirror = true;
        setRotation(Shape8, 0F, 0F, 0F);
        Shape9 = new ModelRenderer(this, 72, 47);
        Shape9.addBox(0F, 0F, 0F, 6, 15, 1);
        Shape9.setRotationPoint(3F, 3F, -7F);
        Shape9.setTextureSize(256, 256);
        Shape9.mirror = true;
        setRotation(Shape9, 0F, 0F, 0F);
        Shape10 = new ModelRenderer(this, 0, 0);
        Shape10.addBox(0F, 0F, 0F, 1, 1, 14);
        Shape10.setRotationPoint(2F, 3F, -7F);
        Shape10.setTextureSize(256, 256);
        Shape10.mirror = true;
        setRotation(Shape10, 0F, 0F, 0F);
        Shape11 = new ModelRenderer(this, 0, 27);
        Shape11.addBox(0F, 0F, 0F, 1, 3, 2);
        Shape11.setRotationPoint(2F, 4F, 5F);
        Shape11.setTextureSize(256, 256);
        Shape11.mirror = true;
        setRotation(Shape11, 0F, 0F, 0F);
        Shape12 = new ModelRenderer(this, 20, 18);
        Shape12.addBox(0F, 0F, 0F, 1, 3, 2);
        Shape12.setRotationPoint(2F, 4F, -7F);
        Shape12.setTextureSize(256, 256);
        Shape12.mirror = true;
        setRotation(Shape12, 0F, 0F, 0F);
        Shape13 = new ModelRenderer(this, 0, 18);
        Shape13.addBox(0F, 0F, 0F, 1, 3, 2);
        Shape13.setRotationPoint(2F, 4F, -1F);
        Shape13.setTextureSize(256, 256);
        Shape13.mirror = true;
        setRotation(Shape13, 0F, 0F, 0F);
        Shape14 = new ModelRenderer(this, 38, 23);
        Shape14.addBox(0F, 0F, 0F, 7, 1, 12);
        Shape14.setRotationPoint(3F, 2F, -6F);
        Shape14.setTextureSize(256, 256);
        Shape14.mirror = true;
        setRotation(Shape14, 0F, 0F, 0F);
        Shape15 = new ModelRenderer(this, 23, 88);
        Shape15.addBox(0F, 0F, 0F, 3, 5, 4);
        Shape15.setRotationPoint(-10F, 3F, -2F);
        Shape15.setTextureSize(256, 256);
        Shape15.mirror = true;
        setRotation(Shape15, 0F, 0F, 0F);
        Shape16 = new ModelRenderer(this, 23, 73);
        Shape16.addBox(0F, 0F, 0F, 4, 5, 3);
        Shape16.setRotationPoint(-10.5F, 3F, -1.5F);
        Shape16.setTextureSize(256, 256);
        Shape16.mirror = true;
        setRotation(Shape16, 0F, 0F, 0F);
        Shape17 = new ModelRenderer(this, 35, 10);
        Shape17.addBox(0F, 0F, 0F, 5, 2, 4);
        Shape17.setRotationPoint(-11F, 1F, -2F);
        Shape17.setTextureSize(256, 256);
        Shape17.mirror = true;
        setRotation(Shape17, 0F, 0F, 0F);
        Shape18 = new ModelRenderer(this, 34, 0);
        Shape18.addBox(0F, 0F, 0F, 4, 2, 5);
        Shape18.setRotationPoint(-10.5F, 1F, -2.5F);
        Shape18.setTextureSize(256, 256);
        Shape18.mirror = true;
        setRotation(Shape18, 0F, 0F, 0F);
        Shape20 = new ModelRenderer(this, 0, 67);
        Shape20.addBox(0F, 0F, 0F, 4, 4, 1);
        Shape20.setRotationPoint(3F, 20F, 7F);
        Shape20.setTextureSize(256, 256);
        Shape20.mirror = true;
        setRotation(Shape20, 0F, 0F, 0F);
        Shape21 = new ModelRenderer(this, 0, 77);
        Shape21.addBox(0F, 0F, 0F, 4, 4, 1);
        Shape21.setRotationPoint(-4F, 20F, 7F);
        Shape21.setTextureSize(256, 256);
        Shape21.mirror = true;
        setRotation(Shape21, 0F, 0F, 0F);
        Shape22 = new ModelRenderer(this, 0, 90);
        Shape22.addBox(0F, 0F, 0F, 4, 4, 1);
        Shape22.setRotationPoint(-11F, 20F, 7F);
        Shape22.setTextureSize(256, 256);
        Shape22.mirror = true;
        setRotation(Shape22, 0F, 0F, 0F);
        Shape23 = new ModelRenderer(this, 0, 114);
        Shape23.addBox(0F, 0F, 0F, 4, 4, 1);
        Shape23.setRotationPoint(-4F, 20F, -8F);
        Shape23.setTextureSize(256, 256);
        Shape23.mirror = true;
        setRotation(Shape23, 0F, 0F, 0F);
        Shape24 = new ModelRenderer(this, 0, 124);
        Shape24.addBox(0F, 0F, 0F, 4, 4, 1);
        Shape24.setRotationPoint(3F, 20F, -8F);
        Shape24.setTextureSize(256, 256);
        Shape24.mirror = true;
        setRotation(Shape24, 0F, 0F, 0F);
        Shape25 = new ModelRenderer(this, 0, 102);
        Shape25.addBox(0F, 0F, 0F, 4, 4, 1);
        Shape25.setRotationPoint(-11F, 20F, -8F);
        Shape25.setTextureSize(256, 256);
        Shape25.mirror = true;
        setRotation(Shape25, 0F, 0F, 0F);
        Shape26 = new ModelRenderer(this, 81, 24);
        Shape26.addBox(0F, 0F, 0F, 15, 1, 7);
        Shape26.setRotationPoint(-13F, 16F, -3.5F);
        Shape26.setTextureSize(256, 256);
        Shape26.mirror = true;
        setRotation(Shape26, 0F, 0F, 0F);
        Shape27 = new ModelRenderer(this, 39, 96);
        Shape27.addBox(0F, 0F, 0F, 1, 6, 10);
        Shape27.setRotationPoint(-16F, 17F, 0F);
        Shape27.setTextureSize(256, 256);
        Shape27.mirror = true;
        setRotation(Shape27, 0F, 0.3839724F, 0F);
        Shape29 = new ModelRenderer(this, 39, 74);
        Shape29.addBox(0F, 0F, 0F, 1, 6, 10);
        Shape29.setRotationPoint(-12.3F, 17F, -9.3F);
        Shape29.setTextureSize(256, 256);
        Shape29.mirror = true;
        setRotation(Shape29, 0F, -0.3839724F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
        Shape9.render(f5);
        Shape10.render(f5);
        Shape11.render(f5);
        Shape12.render(f5);
        Shape13.render(f5);
        Shape14.render(f5);
        Shape15.render(f5);
        Shape16.render(f5);
        Shape17.render(f5);
        Shape18.render(f5);
        Shape20.render(f5);
        Shape21.render(f5);
        Shape22.render(f5);
        Shape23.render(f5);
        Shape24.render(f5);
        Shape25.render(f5);
        Shape26.render(f5);
        Shape27.render(f5);
        Shape29.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
