/*
 * Jaffas and more!
 * author: monnef
 */

// Date: 28/05/2013 15:55:32
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package monnef.jaffas.technic.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCompostTank extends ModelBase {
    //fields
    ModelRenderer Floor;
    ModelRenderer Bar4;
    ModelRenderer Bar2;
    ModelRenderer Bar1;
    ModelRenderer Bar3;
    ModelRenderer Side2;
    ModelRenderer Side1;
    ModelRenderer Side4;
    ModelRenderer Side3;
    ModelRenderer Compost;

    public ModelCompostTank() {
        textureWidth = 256;
        textureHeight = 512;

        Floor = new ModelRenderer(this, 0, 352);
        Floor.addBox(0F, 0F, 0F, 48, 2, 48);
        Floor.setRotationPoint(-8F, 22F, -8F);
        Floor.setTextureSize(256, 512);
        Floor.mirror = true;
        setRotation(Floor, 0F, 0F, 0F);
        Bar4 = new ModelRenderer(this, 0, 0);
        Bar4.addBox(0F, 0F, 0F, 2, 32, 2);
        Bar4.setRotationPoint(37F, -10F, 37F);
        Bar4.setTextureSize(256, 512);
        Bar4.mirror = true;
        setRotation(Bar4, 0F, 0F, 0F);
        Bar2 = new ModelRenderer(this, 0, 0);
        Bar2.addBox(0F, 0F, 0F, 2, 32, 2);
        Bar2.setRotationPoint(37F, -10F, -7F);
        Bar2.setTextureSize(256, 512);
        Bar2.mirror = true;
        setRotation(Bar2, 0F, 0F, 0F);
        Bar1 = new ModelRenderer(this, 0, 0);
        Bar1.addBox(0F, 0F, 0F, 2, 32, 2);
        Bar1.setRotationPoint(-7F, -10F, -7F);
        Bar1.setTextureSize(256, 512);
        Bar1.mirror = true;
        setRotation(Bar1, 0F, 0F, 0F);
        Bar3 = new ModelRenderer(this, 0, 0);
        Bar3.addBox(0F, 0F, 0F, 2, 32, 2);
        Bar3.setRotationPoint(-7F, -10F, 37F);
        Bar3.setTextureSize(256, 512);
        Bar3.mirror = true;
        setRotation(Bar3, 0F, 0F, 0F);
        Side2 = new ModelRenderer(this, 128, 128);
        Side2.addBox(0F, 0F, 0F, 42, 30, 1);
        Side2.setRotationPoint(-5F, -8F, 37F);
        Side2.setTextureSize(256, 512);
        Side2.mirror = true;
        setRotation(Side2, 0F, 0F, 0F);
        Side1 = new ModelRenderer(this, 128, 128);
        Side1.addBox(0F, 0F, 0F, 42, 30, 1);
        Side1.setRotationPoint(-5F, -8F, -6F);
        Side1.setTextureSize(256, 512);
        Side1.mirror = true;
        setRotation(Side1, 0F, 0F, 0F);
        Side4 = new ModelRenderer(this, 128, 0);
        Side4.addBox(0F, 0F, 0F, 1, 30, 42);
        Side4.setRotationPoint(37F, -8F, -5F);
        Side4.setTextureSize(256, 512);
        Side4.mirror = true;
        setRotation(Side4, 0F, 0F, 0F);
        Side3 = new ModelRenderer(this, 128, 0);
        Side3.addBox(0F, 0F, 0F, 1, 30, 42);
        Side3.setRotationPoint(-6F, -8F, -5F);
        Side3.setTextureSize(256, 512);
        Side3.mirror = true;
        setRotation(Side3, 0F, 0F, 0F);
        Compost = new ModelRenderer(this, 0, 256);
        Compost.addBox(0F, 0F, 0F, 42, 28, 42);
        Compost.setRotationPoint(-5F, -6F, -5F);
        Compost.setTextureSize(256, 512);
        Compost.mirror = true;
        setRotation(Compost, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        render(f5);
    }

    public void render(float f5) {
        Floor.render(f5);
        Bar4.render(f5);
        Bar2.render(f5);
        Bar1.render(f5);
        Bar3.render(f5);
        Side2.render(f5);
        Side1.render(f5);
        Side4.render(f5);
        Side3.render(f5);
        Compost.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
    }

}
